#!/usr/bin/env python3
"""Generate references/check-index.md from the success-criterion catalogue.

Reads references/sc-*.md, finds every "### WCAG-<sc> — <title> (Level X)" section,
and writes a table: ID | SC | Level | Principle | New in 2.2 | Testability | axe rules | File.

Usage:
  gen_check_index.py            write references/check-index.md
  gen_check_index.py --check    verify the file is current and the catalogue is complete

Exit codes: 0 ok, 1 check failed (stale index or catalogue problem), 2 usage/error.
Stdlib only; Python 3.9+.
"""
import argparse
import re
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REFS = ROOT / "references"
INDEX = REFS / "check-index.md"

PRINCIPLES = {"1": "Perceivable", "2": "Operable", "3": "Understandable", "4": "Robust"}
# WCAG 2.2 (2024-12-12): 87 SC sections = 31 A + 24 AA + 31 AAA + 4.1.1 (obsolete).
EXPECTED_LEVELS = {"A": 31, "AA": 24, "AAA": 31, "obsolete": 1}
EXPECTED_TOTAL = 87
EXPECTED_NEW = {"2.4.11", "2.4.12", "2.4.13", "2.5.7", "2.5.8", "3.2.6", "3.3.7", "3.3.8", "3.3.9"}
TESTABILITY = {"automated", "assisted", "manual"}

HEAD_RE = re.compile(
    r"^### WCAG-(?P<sc>\d+\.\d+\.\d+) — (?P<title>.+?) "
    r"\((?:Level (?P<level>A{1,3})|(?P<obsolete>Obsolete[^)]*))\)(?P<new> — new in 2\.2)?\s*$"
)
TEST_RE = re.compile(r"^- \*\*Testability:\*\* (?P<t>\w+)")
AXE_RE = re.compile(r"^\s+- \*\*axe-core rules \((?P<ver>[^)]+)\):\*\* (?P<rules>.+)$")


def sc_key(sc):
    return tuple(int(p) for p in sc.split("."))


def parse_catalogue():
    rows, problems, axe_versions = [], [], set()
    files = sorted(REFS.glob("sc-*.md"))
    if not files:
        raise FileNotFoundError(f"no sc-*.md files under {REFS}")
    for f in files:
        cur = None
        for n, line in enumerate(f.read_text(encoding="utf-8").splitlines(), 1):
            m = HEAD_RE.match(line)
            if m:
                cur = {
                    "sc": m["sc"], "title": m["title"],
                    "level": m["level"] or "obsolete",
                    "principle": m["sc"].split(".")[0],
                    "new": bool(m["new"]),
                    "testability": None, "axe": None,
                    "file": f.name, "line": n,
                }
                rows.append(cur)
                continue
            if line.startswith("### WCAG-"):
                problems.append(f"{f.name}:{n}: malformed SC heading: {line}")
                cur = None
                continue
            if cur is None:
                continue
            m = TEST_RE.match(line)
            if m and cur["testability"] is None:
                cur["testability"] = m["t"]
                continue
            m = AXE_RE.match(line)
            if m and cur["axe"] is None:
                axe_versions.add(m["ver"])
                rules = m["rules"].strip()
                cur["axe"] = [] if rules == "none" else re.findall(r"`([^`]+)`", rules)
    return rows, problems, axe_versions


def validate(rows, problems):
    errs = list(problems)
    seen = Counter(r["sc"] for r in rows)
    errs += [f"duplicate section WCAG-{sc} ({c}x)" for sc, c in seen.items() if c > 1]
    if len(rows) != EXPECTED_TOTAL:
        errs.append(f"expected {EXPECTED_TOTAL} SC sections, found {len(rows)}")
    levels = Counter(r["level"] for r in rows)
    for lv, want in EXPECTED_LEVELS.items():
        if levels.get(lv, 0) != want:
            errs.append(f"level {lv}: expected {want}, found {levels.get(lv, 0)}")
    new = {r["sc"] for r in rows if r["new"]}
    if new != EXPECTED_NEW:
        errs.append(f"new-in-2.2 set mismatch: missing {sorted(EXPECTED_NEW - new)}, extra {sorted(new - EXPECTED_NEW)}")
    for r in rows:
        where = f"{r['file']}:{r['line']} WCAG-{r['sc']}"
        if r["testability"] not in TESTABILITY:
            errs.append(f"{where}: testability missing or not one of {sorted(TESTABILITY)}")
        if r["axe"] is None:
            errs.append(f"{where}: missing '**axe-core rules (...):**' line")
        expected_file = f"sc-{r['principle']}-{PRINCIPLES.get(r['principle'], '?').lower()}.md"
        if r["file"] != expected_file:
            errs.append(f"{where}: belongs in {expected_file}")
    return errs


def render(rows, axe_versions):
    rows = sorted(rows, key=lambda r: sc_key(r["sc"]))
    lv = Counter(r["level"] for r in rows)
    by_p = Counter(r["principle"] for r in rows)
    by_pl = Counter((r["principle"], r["level"]) for r in rows)
    tst = Counter(r["testability"] for r in rows)
    ver = ", ".join(sorted(axe_versions)) or "unknown"
    out = [
        "# WCAG 2.2 check index",
        "",
        "<!-- GENERATED by tools/gen_check_index.py from references/sc-*.md. Do not edit by hand; "
        "run `python3 tools/gen_check_index.py` (or `--check` in CI). -->",
        "",
        "One row per WCAG 2.2 success-criterion section. The check ID `WCAG-<sc>` is the key used in tool findings "
        "(`\"sc\"` field). SC titles are quoted from WCAG 2.2 (W3C Recommendation, 12 December 2024, "
        "<https://www.w3.org/TR/WCAG22/>; Copyright © 2024 World Wide Web Consortium, "
        "<https://www.w3.org/copyright/document-license-2023/>); see `NOTICE`.",
        "",
        f"axe rules: axe-core {ver} rules whose metadata tags map to the SC (`wcagNNN` tags). "
        "Rules tagged experimental or deprecated in axe are marked as such.",
        "",
        "## Counts",
        "",
        "| Principle | A | AA | AAA | Obsolete | Total |",
        "|---|---|---|---|---|---|",
    ]
    for p, name in PRINCIPLES.items():
        out.append(f"| {p} {name} | {by_pl[(p, 'A')]} | {by_pl[(p, 'AA')]} | {by_pl[(p, 'AAA')]} | "
                   f"{by_pl[(p, 'obsolete')]} | {by_p[p]} |")
    out.append(f"| **All** | **{lv['A']}** | **{lv['AA']}** | **{lv['AAA']}** | **{lv['obsolete']}** | **{len(rows)}** |")
    out += [
        "",
        f"Active criteria: {len(rows) - lv['obsolete']}. Level AA audit scope (A + AA): {lv['A'] + lv['AA']}. "
        f"New in 2.2: {sum(r['new'] for r in rows)}. "
        f"Testability: automated {tst['automated']}, assisted {tst['assisted']}, manual {tst['manual']}.",
        "",
        "## Index",
        "",
        "| ID | SC | Level | Principle | New in 2.2 | Testability | axe rules | File |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        anchor = "wcag-" + r["sc"].replace(".", "-")
        axe = ", ".join(f"`{a}`" for a in r["axe"]) if r["axe"] else "—"
        out.append(
            f"| WCAG-{r['sc']} | {r['title']} | {r['level']} | {r['principle']} {PRINCIPLES[r['principle']]} | "
            f"{'yes' if r['new'] else ''} | {r['testability']} | {axe} | [{r['file']}]({r['file']}#{anchor}) |"
        )
    return "\n".join(out) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="verify check-index.md is current; do not write")
    try:
        args = ap.parse_args(argv)
    except SystemExit as e:
        return 2 if e.code else 0
    try:
        rows, problems, axe_versions = parse_catalogue()
    except (OSError, UnicodeDecodeError) as e:
        print(f"error: {e}", file=sys.stderr)
        return 2
    errs = validate(rows, problems)
    text = render(rows, axe_versions)
    if args.check:
        current = INDEX.read_text(encoding="utf-8") if INDEX.exists() else None
        if current != text:
            errs.append(f"{INDEX.relative_to(ROOT)} is stale or missing; run tools/gen_check_index.py")
        for e in errs:
            print(f"FAIL: {e}", file=sys.stderr)
        if not errs:
            lv = Counter(r["level"] for r in rows)
            print(f"ok: {len(rows)} SC sections (A {lv['A']}, AA {lv['AA']}, AAA {lv['AAA']}, obsolete {lv['obsolete']}); index current")
        return 1 if errs else 0
    for e in errs:
        print(f"WARN: {e}", file=sys.stderr)
    INDEX.write_text(text, encoding="utf-8")
    print(f"wrote {INDEX.relative_to(ROOT)} ({len(rows)} rows)")
    return 1 if errs else 0


if __name__ == "__main__":
    sys.exit(main())
